#ifndef MAIN_H
#define MAIN_H

#include "stm32l4xx_hal.h"

#define LED_PIN GPIO_PIN_7
#define LED_GPIO_PORT GPIOE
#define LED_GPIO_CLK_ENABLE() __HAL_RCC_GPIOE_CLK_ENABLE()

// UART1 definitions
#define UART1_TX_PIN GPIO_PIN_9
#define UART1_RX_PIN GPIO_PIN_10
#define UART1_GPIO_PORT GPIOA
#define UART1_GPIO_CLK_ENABLE() __HAL_RCC_GPIOA_CLK_ENABLE()
#define UART1_CLK_ENABLE() __HAL_RCC_USART1_CLK_ENABLE()

// SPI2 definitions for MFRC522
#define SPI2_SCK_PIN GPIO_PIN_13
#define SPI2_MISO_PIN GPIO_PIN_14
#define SPI2_MOSI_PIN GPIO_PIN_15
#define SPI2_CS_PIN GPIO_PIN_8
#define MFRC522_RST_PIN GPIO_PIN_9
#define SPI2_GPIO_PORT GPIOB
#define SPI2_GPIO_CLK_ENABLE() __HAL_RCC_GPIOB_CLK_ENABLE()
#define SPI2_CLK_ENABLE() __HAL_RCC_SPI2_CLK_ENABLE()

extern UART_HandleTypeDef huart1;
extern SPI_HandleTypeDef hspi2;

#endif // MAIN_H